CREATE PROCEDURE SP_I_GENERICO_01
@TIP_ID INT,
@GEN_NOM VARCHAR(150),
@GEN_NOM_CORT VARCHAR(50),
@GEN_LLAVE1 VARCHAR(150),
@GEN_LLAVE2 VARCHAR(150),
@GEN_LLAVE3 VARCHAR(150),
@GEN_DESP VARCHAR(250)
AS
BEGIN
	INSERT INTO [Maestro.Generico] VALUES (@TIP_ID,@GEN_NOM,@GEN_NOM_CORT,@GEN_LLAVE1,@GEN_LLAVE2,@GEN_LLAVE3,@GEN_DESP,1)
END