
CREATE PROCEDURE SP_I_CATEGORIA_01
@CAT_NOM VARCHAR(150),
@CAT_NOM_COMER VARCHAR(150),
@CAT_DESP VARCHAR(250)
AS
BEGIN
	INSERT INTO [Maestro.Categoria] VALUES (@CAT_NOM,@CAT_NOM_COMER,@CAT_DESP,1)
END