CREATE PROCEDURE SP_I_CONTACTO_01
@ENTC_ID INT,
@CONT_NOM VARCHAR(150),
@CONT_CARG VARCHAR(120),
@CONT_EMAIL VARCHAR(150),
@CONT_TELF1 VARCHAR(20),
@CONT_TELF2 VARCHAR(20),
@CONT_CEL1 VARCHAR(20),
@CONT_CEL2 VARCHAR(20),
@CONT_DESC VARCHAR(250)
AS
BEGIN
	INSERT INTO [Maestro.Contacto] VALUES (@ENTC_ID,@CONT_NOM,@CONT_CARG,@CONT_EMAIL,@CONT_TELF1,@CONT_TELF2,@CONT_CEL1,@CONT_CEL2,@CONT_DESC,1)
END