CREATE PROCEDURE [dbo].[SP_I_COTIZACION_01]
@USU_ID INT,
@SED_ID INT
AS
BEGIN
	INSERT INTO [Li.Cotizacion] VALUES (0,@USU_ID,@SED_ID,0,0,0,0,0,0,0,'NINGUNA','NINGUNA','NINGUNA','NINGUNA','NINGUNA','NINGUNA','NINGUNA',1)
END