CREATE PROCEDURE [dbo].[SP_I_COMMODITY_01]
@GEN_ID INT,
@COMM_NOM VARCHAR(150),
@COMM_DESC VARCHAR(250)
AS
BEGIN
	INSERT INTO [Maestro.Commodity] 
	VALUES 
	(
		@GEN_ID,
		UPPER(@COMM_NOM),
		UPPER(@COMM_DESC),
		1
	)
END