CREATE PROCEDURE SP_I_SERVICIO_01
@SERV_NOM VARCHAR(150),
@SERV_NOM_COMER VARCHAR(250),
@SERV_DESP VARCHAR(250)
AS
BEGIN
	INSERT INTO [Maestro.Servicio] VALUES (@SERV_NOM,@SERV_NOM_COMER,@SERV_DESP,1)
END