CREATE PROCEDURE [dbo].[SP_I_ENTIDADCABEZERA_01]
@GEN_ID INT,
@ENTC_RAZSOC VARCHAR(150),
@ENTC_RUC VARCHAR(12),
@ENTC_DESC VARCHAR(250),
@ENTC_TELEF1 VARCHAR(12),
@ENTC_TELEF2 VARCHAR(12),
@ENTC_DIREC VARCHAR(250)
AS
BEGIN
	IF (SELECT COUNT(*) FROM [Maestro.EntidadCabezera] WHERE ENTC_RUC=@ENTC_RUC)=0
		BEGIN
			INSERT INTO [Maestro.EntidadCabezera] VALUES (@GEN_ID,UPPER(@ENTC_RAZSOC),@ENTC_RUC,UPPER(@ENTC_DESC),@ENTC_TELEF1,@ENTC_TELEF2,UPPER(@ENTC_DIREC),1)
		END
END