CREATE PROCEDURE SP_L_COTIZACIONCOMMODITY_01
@COT_ID INT
AS
BEGIN
	SELECT     
		LC.COMMD_ID, 
		LC.COT_ID, 
		LC.COMM_ID,
		CM.GEN_NOM AS COMM,
		LC.COMM_BULTOS, 
		LC.UND_ID, 
		UND.GEN_NOM AS UND,
		LC.COMM_PESO, 
		LC.COMM_ALTO, 
		LC.COMM_ANCHO, 
		LC.COMM_LARGO, 
		LC.COMM_TOTAL 
	FROM         
		[Li.Cotizacion_Commodity] LC
		INNER JOIN [Maestro.Generico] CM ON LC.COMM_ID = CM.GEN_ID
		INNER JOIN [Maestro.Generico] UND ON LC.UND_ID = UND.GEN_ID
	WHERE
		LC.COT_ID = @COT_ID AND
		LC.EST = 1
END