CREATE PROCEDURE SP_L_COTIZACION_01
@COT_ID INT
AS
BEGIN
	SELECT 
		COTI.COT_ID,
		USUARIO.USU_ID,
		USUARIO.USU_NOM,
		USUARIO.USU_NOM2,
		USUARIO.USU_EMAIL,
		USUARIO.USU_FIRM,
		USUARIO.USU_FOTO,
		USUARIO.USU_SEX,
		SEDE.SED_ID,
		SEDE.SED_NOM,
		SEDE.SED_NOM2,
		ENTICABE.ENTC_ID AS CLI_ID,
		ENTICABE.ENTC_RAZSOC,
		ENTICABE.ENTC_RUC,
		ENTICABE.ENTC_DIREC,
		CONTACTO.CONT_NOM,
		CONTACTO.CONT_CARG,
		CONTACTO.CONT_EMAIL,
		TIPO.GEN_ID AS TIP_ID,
		TIPO.GEN_NOM AS TIP_NOM,
		COT_ASUN,
		COT_CONT_CORREO,
		COT_SERV_INCLU,
		COT_SERV_NOINCLU,
		COT_REF_INT,
		COT_REF_CLI
	FROM 
		[Li.Cotizacion] COTI
		INNER JOIN [Maestro.Usuario] USUARIO ON COTI.USU_ID = USUARIO.USU_ID
		INNER JOIN [Maestro.Sede] SEDE ON COTI.SED_ID = SEDE.SED_ID
		INNER JOIN [Maestro.EntidadCabezera] ENTICABE ON COTI.CLI_ID = ENTICABE.ENTC_ID
		INNER JOIN [Maestro.Contacto] CONTACTO ON COTI.CONT_ID = CONTACTO.CONT_ID
		INNER JOIN [Maestro.Generico] TIPO ON COTI.TIP_ID = TIPO.GEN_ID
	WHERE
		COTI.COT_ID=@COT_ID AND
		COTI.EST=1
END