CREATE PROCEDURE SP_U_SERVICIO_01
@SERV_ID INT,
@SERV_NOM VARCHAR(150),
@SERV_NOM_COMER VARCHAR(250),
@SERV_DESP VARCHAR(250)
AS
BEGIN
	UPDATE [Maestro.Servicio]
	SET
		SERV_NOM = @SERV_NOM,
		SERV_NOM_COMER = @SERV_NOM_COMER,
		SERV_DESP = @SERV_DESP
	WHERE
		SERV_ID = @SERV_ID
END