CREATE PROCEDURE [dbo].[SP_U_ENTIDADCABEZERA_01]
@ENTC_ID INT,
@GEN_ID INT,
@ENTC_RAZSOC VARCHAR(150),
@ENTC_RUC VARCHAR(12),
@ENTC_DESC VARCHAR(250),
@ENTC_TELEF1 VARCHAR(12),
@ENTC_TELEF2 VARCHAR(12),
@ENTC_DIREC VARCHAR(250)
AS
BEGIN
	UPDATE [Maestro.EntidadCabezera]
	SET
		GEN_ID=@GEN_ID,
		ENTC_RAZSOC=UPPER(@ENTC_RAZSOC),
		ENTC_RUC=@ENTC_RUC,
		ENTC_DESC=UPPER(@ENTC_DESC),
		ENTC_TELF1=@ENTC_TELEF1,
		ENTC_TELF2=@ENTC_TELEF2,
		ENTC_DIREC=@ENTC_DIREC
	WHERE
		ENTC_ID=@ENTC_ID
END