CREATE PROCEDURE [dbo].[SP_U_COMMODITY_01]
@COMM_ID INT,
@GEN_ID INT,
@COMM_NOM VARCHAR(150),
@COMM_DESC VARCHAR(250)
AS
BEGIN
	UPDATE [Maestro.Commodity] 
	SET
		GEN_ID = @GEN_ID,
		COMM_NOM = @COMM_NOM,
		COMM_DESC = @COMM_DESC
	WHERE
		COMM_ID = @COMM_ID
END