CREATE PROCEDURE SP_U_TIPO_01
@TIP_ID INT,
@TIP_NOM VARCHAR(150),
@TIP_NOM_CORT VARCHAR(50),
@TIP_DESP VARCHAR(250)
AS
BEGIN
	UPDATE [Maestro.Tipo] 
	SET
		TIP_NOM = @TIP_NOM,
		TIP_NOM_CORT = @TIP_NOM_CORT,
		TIP_DESP = @TIP_DESP
	WHERE
		TIP_ID = @TIP_ID
END