CREATE PROCEDURE [dbo].[SP_U_PUERTO_01]  
@PUER_ID INT,  
@GEN_ID INT,  
@PUER_NOM VARCHAR(150),  
@PUER_DESC VARCHAR(250)  
AS  
BEGIN  
 UPDATE [Maestro.Puerto]   
 SET  
  GEN_ID = @GEN_ID,  
  PUER_NOM = @PUER_NOM,  
  PUER_DESC = @PUER_DESC  
 WHERE  
  PUER_ID = @PUER_ID  
END