CREATE PROCEDURE SP_U_CATEGORIA_01
@CAT_ID INT,
@CAT_NOM VARCHAR(150),
@CAT_NOM_COMER VARCHAR(150),
@CAT_DESP VARCHAR(250)
AS
BEGIN
	UPDATE [Maestro.Categoria] 
	SET
		CAT_NOM = @CAT_NOM,
		CAT_NOM_COMER = @CAT_NOM_COMER,
		CAT_DESP = @CAT_DESP
	WHERE
		CAT_ID = @CAT_ID	 
END